version: "3"
services:
  # uncomment comps_etl if you need initdb at first run when you pull the repository
  # currently dumping airflow tables on cmbs db -> point to a different db if need be :)
  comps_etl:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PGHOST=localhost
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]",
             "CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"
      ]
      interval: 30s
      timeout: 30s
      retries: 3

# use if you have this environmental variable defined on your local machine.
#environment:
#      - PGHOST
#      - PGPORT
#      - PGUSER
#      - PGDATABASE
#      - PGPASSWORD
#      - AURORAPASSWORD
#      - AURORAUSER
#      - AURORADATABASE
#      - AURORAHOST
#      - ADUSER
#      - ADPASSWORD
